cursor #bbc2cf
cursor_text_color #cbccd1

foreground            #bbc2cf
background            #1c1f24
selection_foreground  #16161e
selection_background  #c678dd
url_color             #51afef

color0   #1a1b26
color1   #ff457f
color2   #51ef64
color3   #fff445
color4   #2e9ae3
color5   #00416e
color6   #51afef
color7   #e7f2fa
color8   #8b959b
color9   #ff80a7
color10  #88ff97
color11  #fff888
color12  #6fc4ff
color13  #88cfff
color14  #b3e0ff
color15  #f6fbff
